ddns-update-style interim;

authoritative;
allow booting;
allow bootp;

ignore client-updates;
set vendorclass = option vendor-class-identifier;
option system-arch code 93 = unsigned integer 16;



subnet 1.1.1.0 netmask 255.255.255.255 {                 #指定为那个网段分配网络参数
   range 9.9.9.10   9.9.9.20;               #设置准备为客户端分配的IP地址范围
   option domain-name-servers 114.114.114.114;             #设置分配给客户端的DNS服务器地址
   option routers 1.1.1.1;                         #设置分配给客户端的网关地址。
   default-lease-time 600;                              # 地址租赁时间 600秒后失效
   max-lease-time 1080;                                 #最大租约时间12小时
   next-server 1.1.1.2;       # 下一个要访问的地址，就是tftp地址。默认使用本机IP

      class "pxeclients" {
          match if substring (option vendor-class-identifier, 0, 9) = "PXEClient";


          # 核心匹配条件：判断 option system-arch  的数值
          if option system-arch = 00:00 {
          # BIOS/Legacy 启动 
             #filename "pxelinux.0";
             #filename "snponly_x86.efi";
             #filename "ipxe_x86.efi";
             #filename "grubx86.efi";
          } 
          #  x86_64 UEFI 1
          else if option system-arch = 00:06 {
             filename "grubx64.efi";
             #filename "snponly_x86.efi";
             #filename "ipxe_x86.efi";
          }

          ## x86_64 UEFI 2 -default
          else if option system-arch = 00:07 {
             filename "grubx64.efi";
             #filename "ipxe_x86.efi";
             #filename "snponly_x86.efi";
             #Install  Esxi
             #filename "esxi7/bootx64.efi";

          }
         
          ## x86_64 UEFI 3
          else if option system-arch = 00:08 {
             filename "grubx64.efi";
             #filename "grubx64.efi";
             #filename "snponly_x86.efi";
             #filename "ipxe_x86.efi";
          }
       
          ## x86_64 UEFI 4
          else if option system-arch = 00:09 {
             filename "grubaa64.efi";
             #filename "ipxe_arm.efi";
             #filename "snponly_arm.efi";
          }

          # ARM64 UEFI 鲲鹏
          else if option system-arch = 00:11 {
             filename "grubaa64.efi";
             #filename "snponly_arm.efi";
             #filename "ipxe_arm.efi";
          }

          # ARM64 (aka arm 64 bit)
          else if option system-arch = 00:0b {
             filename "grubaa64.efi";
             #filename "snponly_arm.efi";
             #filename "ipxe_arm.efi";
          }
          
          # FIXME add petitboot support for ppc64(le)
          else if option system-arch = 00:0e {
              filename "grub.ppc64le";
          }

          # 兜底
          else {
             filename "grubx64.efi";
             #filename "snponly_x86.efi";
             #filename "ipxe_x86.efi";
          }
      }

}


