worker_processes auto;
worker_rlimit_nofile 524288;

events {
    worker_connections 32768;
    use epoll;
    multi_accept on;
}

http {
    include mime.types;
    default_type application/octet-stream;
    access_log off;
    
    sendfile off;
    tcp_nopush on;

    #tcp_nopush off;
    tcp_nodelay    on;


    keepalive_timeout 30;
    
    aio threads;
    directio 2m;
    output_buffers 2 2m;
    sendfile_max_chunk 2m;
    
    # [20台以上使用]全局限速：前 5MB 不限速，之后限速 4MB/s
    #limit_rate_after 5m;
    #limit_rate 4m;

    server {
        listen 80 backlog=131072;
        server_name _;
        root /var/lib/tftpboot;
        
        location / {
            directio 2m;
            autoindex on;
            limit_rate 10m;       # 其他文件每台限 20MB/s
        }
        location ~* \.img$ {
            limit_rate 20m;
            directio 2m;
            autoindex on;
        }
    }
}
